version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: hybrid_analytics_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d hybrid_analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.6.0
    restart: always
    environment:
      MEILI_MASTER_KEY: aSampleMasterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  postgres_data:
  meili_data: